### ISSUE TITLE
Conflicting installation directory

### ISSUE THREAD

**Issue by szepeviktor** [moloni-pt/woocommerce#16]
https://github.com/moloni-pt/woocommerce/blob/e52a726768d7822d6613457f278f09d4e2f3c2ad/composer.json#L2-L5

When installed with Composer it would go in `wp-content/plugins/woocommerce`.

@fabiocorreia95 Please consider choosing another name. e.g. `moloni-woocommerce`

**Comment by fabiocorreia95** [comment]
Hello,

Thank you, will do.
