### ISSUE TITLE
Portuguese typos

### ISSUE THREAD

**Issue by szepeviktor** [moloni-pt/woocommerce#18]
`actualizados -> atualizados` `actualiza -> atualiza` `Actualizar -> Atualizar`

`automáticamente -> automaticamente`

`acção -> ação`

`encontadas -> encontradas`

`seleccionar -> selecionar` `seleccionado -> selecionado`

_Eu não falo nenhuma língua!_ 🙃 Hunspell told me these are unknown words. Another one was "resetar" but that must be an imported English word.

Tool: `grep -rho "\\(__\\|esc_html_e\\|esc_html__\\)([^)]\\+)"`

**Comment by fabiocorreia95** [comment]
Hello,

The words you report have not yet been updated to the new Portuguese "spelling reform" changes. The word "resetar" is indeed an imported English word, but i will change it as well.

Thank you.

**Comment by szepeviktor** [comment]
You're very welcome.
