### ISSUE TITLE
Criar Icon da factura Moloni dentro da listagem de Encomendas no Woocommerce

### ISSUE THREAD

**Issue by jorgecalwork** [moloni-pt/woocommerce#7]
Precisava de criar um icon em frente de cada encomenda na listagem no Woocommerce para quando se clicar nesse icon fazer o download da factura que é criada automaticamente na Moloni. 

Assim não era necessário ir ao site da moloni e imprimir a factura criada. 

Alguém disponível para fazer esta função ?

**Comment by moloni-pt** [comment]
Bom, 

A sugestão que indicou encontra-se já implementada na nova versão do plugin v3.0.59. 
Quando fizer o update ao plugin, irá já ter disponível uma nova opção para adicionar a coluna para download do documento na tabela de encomendas do WooCommerce. 

Queira por favor verificar.
